### ISSUE TITLE
Consider DateFromDateTime

### ISSUE THREAD

**Issue by mj1856** [mj1856/corefx-dateandtime#12]
`Date.DateFromDateTime` is a private method.  It's used to strip off the time information from a `DateTime` and return it as a `Date`.

- Should it be renamed  (`FromDateTime`)
- Should it be made public?

**Comment by rafidka** [comment]
* Yes, I think it is better rename it to FromDateTime, since the the first word (Date) is already implied by the class name, so no need to repeat it.

* I don't see a similar method in DateTime struct, so if this is publicized, I think a similar method in DateTime should be publicized (or added if it doesn't exist) so that the structs align better.

**Comment by mj1856** [comment]
So here are my thoughts...

- I named it `DateFromDateTime` because all usage is coming from within the `Date` struct itself.  If it was called externally, then `Date.FromDateTime` makes a lot of sense, but internally the `Date.` part is usually not given, as it's redundant.

- I'm not sure that it would be good to have the method at all, as it silently strips away the time information.  Using it outside the struct would likely be a mistake.

- As we decompose the functions (see #17), I don't think it will be needed.

**Comment by rafidka** [comment]
I understand. So I guess this should be closed then, no?

**Comment by mj1856** [comment]
Yeah, I think so.  Thanks!
