### ISSUE TITLE
Mockable Today/Now 

### ISSUE THREAD

**Issue by ashmind** [mj1856/corefx-dateandtime#31]
I suggest something like this:
```csharp
public static class TimeProviders {
    [NotNull] public static Func<TimeZoneInfo, Date> TodayInTimeZone { get; set; }
    [NotNull] public static Func<TimeZoneInfo, TimeOfDay> NowInTimeZone { get; set; }
}
```
and using it in various `Date.Today` and `TimeOfDay.Now` calls.

This would allow simple mocking of the Today/Now without wrapping it in custom mockable service (which might be an overkill for simple apps).

**Comment by mj1856** [comment]
Mock the clock!  :smile: 

Yes, there are a few opportunities for that.  Though I'd probably want it to hook into all of the new and existing `.Now` and .`Today` properties, and probably it would make sense to limit the number of functions one would have to write instead of mocking each method separately.

Also we might consider a way to set the "local" time zone explicitly, rather than it always coming from the host OS.

Though, the problem with the implementation you suggested is that it has there's no convenient way to make it thread safe.  You would have to change the clock function or the time zone *globally*.   This makes it difficult to use in unit tests, as you couldn't have different tests using different clock values.  That's also why one usually sees this done as a service, such as Noda Time's `IClock` interface with `SystemClock` and `FakeClock` implementations.

**Comment by ashmind** [comment]
> Though, the problem with the implementation you suggested is that it has there's no convenient way to make it thread safe.

Sure. However the thread-safe mock might be a separate package (e.g. something using CallContext). And while it is nice to have thread-safe tests, having at least *some* easy way to test would be great.

> That's also why one usually sees this done as a service, such as Noda Time's IClock interface with SystemClock and FakeClock implementations.

I know and that's what we use normally, however it is a hassle for small projects and with legacy code -- so it would be good if framework provided at least a basic way.

**Comment by mj1856** [comment]
We can consider including `IClock`, `SystemClock` and `FakeClock`, but there's just not a good pattern for wiring these up to `DateTime.Now` and similar properties.  The best we could do is to include a Roslyn Analyzer warning to recommend pulling the time from a clock instead of directly.  We're going to write a handful of analyzers, so this could be included.

I'm closing this for now, but will open a new issue to track this after the move to corefxlab.
