### ISSUE TITLE
TimeOfDay => Time ?

### ISSUE THREAD

**Issue by ashmind** [mj1856/corefx-dateandtime#32]
Name `TimeOfDay`, while accurate, feels a bit over-complicated for a fundamental system type.
I suggest just `Time`.

After all, SQL Server just names it `time`, type `DateTime` means `Date`+`Time`, etc.

**Comment by mj1856** [comment]
There are two motivations for that.

1. To clearly distinguish from `TimeSpan`
2. To prevent naming conflicts with a possible `System.Time` namespace

1 applies still, but I'm not sure that 2 will matter.  It's still possible there could be a `System.Time` nuget package, but likely it will just use the `System` namespace.

**Comment by mj1856** [comment]
Sorry, didn't mean that to sound definitive.  I'll keep this open so other folks can chime in.  In the end though it will likely be someone from the core framework team that makes the final decision.

**Comment by ashmind** [comment]
> To clearly distinguish from TimeSpan
Hmm, do you means the `Days` part of `TimeSpan` that isn't relevant to `Time`?
Because for spans < 1 day relationship between `Time` and `TimeSpan` is pretty clear.

It even makes sense to have `operator -` on `Time` that returns `TimeSpan`.

**Comment by mj1856** [comment]
Fundamentally, they are different.  `TimeSpan` is for elapsed durations of time.  They can be >= 24 hours, and they can be negative to represent moving backwards on a time line (ex: "3 hours ago").

`TimeOfDay` represents a fixed position on a 24-hour clock.  In addition to the range requirements, it's modeled as a circular clock with regard to arithmetic (two hours past 23:00 is 01:00).

There's also the general problem of thinking of it as "time elapsed since midnight", since not all days have a local midnight, and even when they do, there's no guarantee that time isn't skipped or repeated over the span in question.  While we're not modeling `TimeOfDay` as a time-zone-aware clock, the distinction is still useful.

Oh, and of course, once we definitively know that it's a time-of-day, we can support 12-hour-clock semantics as well.  (am/pm)

**Comment by mj1856** [comment]
WRT the subtraction operator, I have one for `TimeOfDay - TimeSpan = TimeOfDay`, but I didn't yet create one for `TimeOfDay - TimeOfDay = TimeSpan`.  I did add a [`CalculateDuration`](https://github.com/mj1856/corefx-dateandtime/blob/12a791eba56e12f538b116134aec27b98e5d326e/System.DateAndTime/TimeOfDay.cs#L419-L430) method though.

I suppose a subtraction operator would be ok, since order-of-operations is already implied with subtraction.  Though one would have to realize that while `02:00 - 01:00 == 1 hour`, the inverse would be `01:00 - 02:00 == 23 hours`.

**Comment by ashmind** [comment]
> we can support 12-hour-clock semantics as well. (am/pm)

Interesting. Is there a use case for those other than in formatting?

> Though one would have to realize that while 02:00 - 01:00 == 1 hour, the inverse would be 01:00 - 02:00 == 23 hours.

Why not -1h? Negative `TimeSpan` seems more intuitive here.
If one event happened at 2:00 and other at 1:00 within one day (and having two times in calculation implies same day to me), second would be earlier than first by an hour, not later by 23.

**Comment by mj1856** [comment]
Wrote this up as #33.

> having two times in calculation implies same day to me

Not necessarily.  Remember, this is a 24-hour circular clock.  There's no associated date.  If you pick two points on the clock and ask for the duration between them, it's always going to calculate in a clockwise motion.

**Comment by mj1856** [comment]
It's more intuative if you think about values that cross midnight, such as `02:00 - 22:00 = 4 hours`.  This happens in real-world scenarios when employees work night shifts.
