### ISSUE TITLE
Some comments on the code

### ISSUE THREAD

**Issue by tarekgh** [mj1856/corefx-dateandtime#5]
I posted this in the original discussion thread but it make sense to have it here
 
Thanks Matt for your effort. I took a quick look at the Date type and here is some notes and questions:
•does Date need to implement IConvertible interface. I think it is needed
•Date will be exactly like DateTime in term of supporting Gregorian dates only. this can be ok if this satisfy all scenarios we are introducing Date for (SQL, Xml...etc.). if there is any other scenarios need to work with other calendars we'll need to either add such support here or we'll have another type like CalendarDate or so.
•Did you think in supporting B.C dates? just raising the thought
•does it make it easier if you store ticks instead of daynumber? avoid converting to ticks in many places
•ToString(string format), would be ok if some one passing format include time? not a problem but just wondering 
•In general from my experience with DateTime, Parse/TryParse is really problem and always causing problems especially when changing the culture default date/time patterns. I suggest we don't support Parse/TryParse and force only ParseExact/TryParseExact
•renaming DateFromDateTime to FromDateTime would be better I guess
•if we have Add/Subtract methods, then I think we need to limit the parameters to positive values. otherwise we should have Add only. I am trying to limit the confusion when using it
•I like the implicit cast operator :-) 

Thanks again Matt

**Comment by mj1856** [comment]
Spliting into separate issues for discussion.

**Comment by mj1856** [comment]
Split as follows:

- #6 - Implement IConvertible?
- #7 - Support additional calendars
- #8 - Support BCE dates?
- #9 - Internal storage format
- #10 - Constrain format strings
- #11 - Consider removing Parse/TryParse
- #12 - Consider DateFromDateTime
- #13 - Limit range of add/subtract operations

**Comment by rafidka** [comment]
Adding more comments here:

* I noticed that in many places in the code you explicitly used 'Date' to define a variable, rather than using 'var' (type deduction). I understood from corefix documentation that we can use var var' when it is clear what the object being defined is, no?
* I think At() method should be renamed to ToDateTimeAt(), to align it with the method ToDateTimeAtMidnight(). Or, the latter can be renamed to AtMidnight() (though I prefer the first, as I couldn't know what the method At() does before reading the code.)
* How is the constructor Date(int year, int dayOfYear) useful? It doesn't seem to have a counterpart in DateTime even though the latter does have a constructor that takes date components only, i.e. year, month, and day.
* Why TodayLocal not Today, just like it is DateTime.Now rather than DateTime.LocalNow?

**Comment by mj1856** [comment]
Feel free to use `var`.  If the coreclr/corefx team doesn't like it, they can always adjust.  Just don't go crazy replacing with `var` everywhere just because it's possible.

Agreed about the naming recommendations.  While `At` is simpler, it would be more aligned with existing conventions to use `ToDateTimeAt`.

The `year, dayOfYear` constructor I think is important, as day-of-year is often used in financial applications.  I think that it could probably be added to `DateTime` also, but that would imply midnight.  In the case of our `Date` object, it aligns better because there's no specific time assigned.

Agree about `Today` naming. See [my comment here](https://github.com/mj1856/corefx-dateandtime/issues/15#issuecomment-78365209)

**Comment by Clockwork-Muse** [comment]
What's the scope of this?  I mean, is this in anticipation of a complete date/time library (support for custom calendars and internationalization, querying, etc), or just a narrow set of features?

**Comment by mj1856** [comment]
@Clockwork-Muse - We're not designing an entire date/time library, no.  The scope is currently limited to the following:

- `System.Date` - A date-only data type
- `System.TimeOfDay` - A time-only data type
- Reasonable minimal extensions to `System.DateTime`, `System.DateTimeOffset`, `System.TimeSpan` and `System.TimeZoneInfo`.

There will be some minimal interaction with `System.Globalization.Calendar`, similar to how `System.DateTime` uses it, as discussed in #7.

We'll also want lots of unit tests, and example usage scenarios.

We will align to the conventions used by the existing types whenever possible.  The general idea to prove out what `System.Date` and `System.TimeOfDay` would look like if they were already part of the .NET Framework because we feel they are missing, and hope that at some point they will be merged in.

Put another way, we feel strongly that:
- It is a mistake to store date-only information into a date+time structure by setting the time to midnight, such as currently is done with `DateTime.Date` and `DateTime.Today
- It is a mistake to store time-only information into a date+time structure by setting the date to an arbitrary or current value, such as is done when with `DateTime.Parse("12:00")`
- It is a mistake to store time-of-day information into an elapsed-time structure (`TimeSpan`), as is currently done with `DateTime.TimeOfDay` and when reading a SQL `time` type from ADO.NET.  We'd like to see [the data type mapping page](https://msdn.microsoft.com/en-us/library/cc716729.aspx) updated such that SQL `date` and `time` types flow naturally to `System.Date` and `System.TimeOfDay` types.

Clearly out of scope:
- A `ZonedDateTime` or similar type combining date+time+offset+timezone.
- Any other timezone-aware types
- Support for other time zone data, such as IANA/TZDB
- Support for dates outside of the range supported by `System.DateTime`
- Support for time with precision less than "Ticks"  (such as nanoseconds)
- Additional format strings beyond the ones supported by `DateTime`
- Additional calendars

All of those can be found in more complete libraries like [Noda Time](http://nodatime.org).  We are just trying to fill in these two very specific gaping holes.
