### ISSUE TITLE
Implement IConvertable?

### ISSUE THREAD

**Issue by mj1856** [mj1856/corefx-dateandtime#6]
`DateTime` implements `IConvertible`, [as seen here](https://github.com/dotnet/coreclr/blob/1644ae12020a1927bb9b7bb7b162ba8b1e8bc73e/src/mscorlib/src/System/DateTime.cs#L1283-L1366).

Should `Date` or `TimeOfDay` also implement `IConvertible`?  If so, how?  Should it just implement `ToDateTime` with the time component set to midnight?

What is an example use case that would require `IConvertable` to be implemented, or make things easier if it were?

Should `IConvertible` itself be extended to include `ToDate` and `ToTimeOfDay` methods?

Note, `TimeSpan` does *not* implement `IConvertible`.

**Comment by paulirwin** [comment]
:+1: for Convert.ChangeType support, which can be used if you don't know the type of the object at runtime. Since Date and TimeOfDay will be fundamental types, having Convert/IConvertible support would be good. Yes, it should just implement ToDateTime. And yes, when this becomes part of mscorlib, IConvertible should be extended to support ToDate and ToTimeOfDay, as well as methods on the System.Convert static class.

**Comment by paulirwin** [comment]
Er, adding methods to IConvertable would be a massively breaking change. I take back the confidence of the last sentence of my previous comment.

**Comment by rafidka** [comment]
I would like to work on this if nobody else is interested :-)

**Comment by rafidka** [comment]
I tried to work on this, but I couldn't even find the IConvertible interface to implement. I am a bit confused as to why it is not there, as the MSDN documentation clearly says the interface is supported on portable .NET as well:

https://msdn.microsoft.com/en-us/library/system.iconvertible%28v=vs.110%29.aspx

Notice the last section about Version Information.

Any idea?

**Comment by rafidka** [comment]
Any update here?

**Comment by mj1856** [comment]
Per Tarek's comment [here](https://github.com/mj1856/corefx-dateandtime/issues/2#issuecomment-89106354) we do not need to support `IConvertible`.
